name: .NET Core

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
    - name: Build with dotnet
      run: dotnet build --configuration Release
